// SPDX-License-Identifier: BSD-3-Clause

// Cross-implementation conformance gate.
//
// This suite verifies the C++/Qt application against the same fixture the Rust
// core verifies against (docs/references/protocol-vectors.json, generated by
// `cargo run -p wirehop-cli -- emit-vectors`). Two independent implementations
// of one wire protocol drift silently; this file plus its Rust counterpart is
// what turns that drift into a red build.
//
// A failure here means one of three things, in order of likelihood: the Rust
// core diverged, this application diverged, or docs/references/PROTOCOL.md is
// ambiguous enough that both readings were defensible. Investigate in that
// order — do not regenerate the fixture to make the build green.

#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QtTest>

#include "crypto.h"
#include "protocol.h"

class ProtocolVectorsTest : public QObject {
    Q_OBJECT
private slots:
    void initTestCase();
    void sessionCodesMatchTheFixture();
    void negotiationParsingMatchesTheFixture();
    void localNegotiationFieldsMatchTheFixture();
    void canonicalMetadataIsParsedIdentically();
    void canonicalResponsesAreParsedIdentically();
private:
    QJsonObject vectors;
};

void ProtocolVectorsTest::initTestCase()
{
    QFile file(QStringLiteral(WIREHOP_VECTORS_PATH));
    QVERIFY2(file.open(QIODevice::ReadOnly),
             qPrintable(QStringLiteral("cannot open %1").arg(WIREHOP_VECTORS_PATH)));
    QJsonParseError error{};
    QJsonDocument doc = QJsonDocument::fromJson(file.readAll(), &error);
    QVERIFY2(doc.isObject(), qPrintable(error.errorString()));
    vectors = doc.object();

    // The fixture must describe the version this build speaks; otherwise every
    // assertion below is checking the wrong contract.
    QCOMPARE(vectors.value("protocol_version").toInt(), static_cast<int>(Protocol::VERSION));
}

void ProtocolVectorsTest::sessionCodesMatchTheFixture()
{
    QJsonArray cases = vectors.value("session_codes").toArray();
    QVERIFY(!cases.isEmpty());

    foreach (const QJsonValue &entry, cases) {
        QJsonObject obj = entry.toObject();
        QByteArray key = QByteArray::fromHex(obj.value("session_key_hex").toString().toLatin1());
        QCOMPARE(key.size(), 32);
        QCOMPARE(Crypto::sessionCodeForKey(key), obj.value("code").toString());
    }
}

void ProtocolVectorsTest::negotiationParsingMatchesTheFixture()
{
    QJsonArray cases = vectors.value("negotiation_parsing").toArray();
    QVERIFY(!cases.isEmpty());

    foreach (const QJsonValue &entry, cases) {
        QJsonObject obj = entry.toObject();
        QString name = obj.value("name").toString();
        QJsonObject input = obj.value("input").toObject();

        int version = Protocol::parseVersion(input.value("protocol_version"));
        QVERIFY2(version == obj.value("expected_version").toInt(),
                 qPrintable(QStringLiteral("version mismatch for case %1").arg(name)));

        QSet<QString> caps = Protocol::parseCaps(input.value("caps"));
        QSet<QString> expected;
        foreach (const QJsonValue &cap, obj.value("expected_caps").toArray())
            expected.insert(cap.toString());
        QVERIFY2(caps == expected,
                 qPrintable(QStringLiteral("caps mismatch for case %1").arg(name)));

        bool ackNegotiated = caps.contains(Protocol::capAck())
                && Protocol::localCaps().contains(Protocol::capAck());
        QVERIFY2(ackNegotiated == obj.value("expected_ack_negotiated").toBool(),
                 qPrintable(QStringLiteral("ack negotiation mismatch for case %1").arg(name)));
    }
}

void ProtocolVectorsTest::localNegotiationFieldsMatchTheFixture()
{
    // What this build emits must equal what the fixture records, including the
    // sorted capability order that makes frames byte-reproducible.
    QJsonObject emitted;
    Protocol::insertNegotiationFields(emitted);

    QJsonObject reference =
            QJsonDocument::fromJson(vectors.value("canonical_responses").toArray()
                                            .at(0).toObject()
                                            .value("canonical_json").toString().toUtf8())
                    .object();

    QCOMPARE(emitted.value("protocol_version").toInt(),
             reference.value("protocol_version").toInt());
    QCOMPARE(QJsonDocument(QJsonObject{{"caps", emitted.value("caps")}}).toJson(QJsonDocument::Compact),
             QJsonDocument(QJsonObject{{"caps", reference.value("caps")}}).toJson(QJsonDocument::Compact));
}

void ProtocolVectorsTest::canonicalMetadataIsParsedIdentically()
{
    QJsonArray cases = vectors.value("canonical_metadata").toArray();
    QVERIFY(!cases.isEmpty());

    foreach (const QJsonValue &entry, cases) {
        QJsonObject obj = entry.toObject();
        QByteArray canonical = obj.value("canonical_json").toString().toUtf8();

        QJsonDocument doc = QJsonDocument::fromJson(canonical);
        QVERIFY(doc.isObject());
        QJsonObject parsed = doc.object();

        QCOMPARE(parsed.value("device_name").toString(), obj.value("device_name").toString());
        QCOMPARE(parsed.value("device_type").toString(), obj.value("device_type").toString());
        QCOMPARE(parsed.value("files").toArray(), obj.value("files").toArray());
        QCOMPARE(Protocol::parseVersion(parsed.value("protocol_version")),
                 static_cast<int>(Protocol::VERSION));
        QVERIFY(Protocol::parseCaps(parsed.value("caps")).contains(Protocol::capAck()));

        // Qt serializes object keys sorted, which is the canonical form the
        // fixture pins; re-serializing must reproduce the exact bytes.
        QCOMPARE(QJsonDocument(parsed).toJson(QJsonDocument::Compact), canonical);
    }
}

void ProtocolVectorsTest::canonicalResponsesAreParsedIdentically()
{
    QJsonArray cases = vectors.value("canonical_responses").toArray();
    QCOMPARE(cases.size(), 2);

    foreach (const QJsonValue &entry, cases) {
        QJsonObject obj = entry.toObject();
        QByteArray canonical = obj.value("canonical_json").toString().toUtf8();

        QJsonDocument doc = QJsonDocument::fromJson(canonical);
        QVERIFY(doc.isObject());
        QJsonObject parsed = doc.object();

        bool accepted = parsed.value("response").toDouble() == 1.0;
        QCOMPARE(accepted, obj.value("accepted").toBool());
        QCOMPARE(Protocol::parseVersion(parsed.value("protocol_version")),
                 static_cast<int>(Protocol::VERSION));
        QCOMPARE(QJsonDocument(parsed).toJson(QJsonDocument::Compact), canonical);
    }

    // The acknowledgment frame the sender matches on.
    QByteArray ack = vectors.value("canonical_ack").toString().toUtf8();
    QJsonDocument ackDoc = QJsonDocument::fromJson(ack);
    QVERIFY(ackDoc.isObject());
    QCOMPARE(ackDoc.object().value("ack").toDouble(), 1.0);
    QCOMPARE(QJsonDocument(ackDoc.object()).toJson(QJsonDocument::Compact), ack);
}

int runProtocolVectorsTest(int argc, char *argv[])
{
    ProtocolVectorsTest test;
    return QTest::qExec(&test, argc, argv);
}

#include "tst_protocolvectors.moc"
